// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/service/agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentControl_StartListener_FullMethodName       = "/service.AgentControl/StartListener"
	AgentControl_StopListener_FullMethodName        = "/service.AgentControl/StopListener"
	AgentControl_GetStatus_FullMethodName           = "/service.AgentControl/GetStatus"
	AgentControl_RegisterInit_FullMethodName        = "/service.AgentControl/RegisterInit"
	AgentControl_NotifyNewConnection_FullMethodName = "/service.AgentControl/NotifyNewConnection"
	AgentControl_BiDiStream_FullMethodName          = "/service.AgentControl/BiDiStream"
	AgentControl_NotifyAgentCheckin_FullMethodName  = "/service.AgentControl/NotifyAgentCheckin"
	AgentControl_HandleUpload_FullMethodName        = "/service.AgentControl/HandleUpload"
)

// AgentControlClient is the client API for AgentControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentControlClient interface {
	StartListener(ctx context.Context, in *ListenerRequest, opts ...grpc.CallOption) (*ListenerResponse, error)
	StopListener(ctx context.Context, in *ListenerRequest, opts ...grpc.CallOption) (*ListenerResponse, error)
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StatusResponse], error)
	RegisterInit(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
	NotifyNewConnection(ctx context.Context, in *ConnectionNotification, opts ...grpc.CallOption) (*ConnectionResponse, error)
	BiDiStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamMessage, StreamMessage], error)
	NotifyAgentCheckin(ctx context.Context, in *AgentCheckinNotification, opts ...grpc.CallOption) (*AgentCheckinResponse, error)
	HandleUpload(ctx context.Context, in *HandleUploadRequest, opts ...grpc.CallOption) (*HandleUploadResponse, error)
}

type agentControlClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentControlClient(cc grpc.ClientConnInterface) AgentControlClient {
	return &agentControlClient{cc}
}

func (c *agentControlClient) StartListener(ctx context.Context, in *ListenerRequest, opts ...grpc.CallOption) (*ListenerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListenerResponse)
	err := c.cc.Invoke(ctx, AgentControl_StartListener_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) StopListener(ctx context.Context, in *ListenerRequest, opts ...grpc.CallOption) (*ListenerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListenerResponse)
	err := c.cc.Invoke(ctx, AgentControl_StopListener_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StatusResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentControl_ServiceDesc.Streams[0], AgentControl_GetStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StatusRequest, StatusResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControl_GetStatusClient = grpc.ServerStreamingClient[StatusResponse]

func (c *agentControlClient) RegisterInit(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, AgentControl_RegisterInit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) NotifyNewConnection(ctx context.Context, in *ConnectionNotification, opts ...grpc.CallOption) (*ConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectionResponse)
	err := c.cc.Invoke(ctx, AgentControl_NotifyNewConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) BiDiStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamMessage, StreamMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentControl_ServiceDesc.Streams[1], AgentControl_BiDiStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMessage, StreamMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControl_BiDiStreamClient = grpc.BidiStreamingClient[StreamMessage, StreamMessage]

func (c *agentControlClient) NotifyAgentCheckin(ctx context.Context, in *AgentCheckinNotification, opts ...grpc.CallOption) (*AgentCheckinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentCheckinResponse)
	err := c.cc.Invoke(ctx, AgentControl_NotifyAgentCheckin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) HandleUpload(ctx context.Context, in *HandleUploadRequest, opts ...grpc.CallOption) (*HandleUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleUploadResponse)
	err := c.cc.Invoke(ctx, AgentControl_HandleUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentControlServer is the server API for AgentControl service.
// All implementations must embed UnimplementedAgentControlServer
// for forward compatibility.
type AgentControlServer interface {
	StartListener(context.Context, *ListenerRequest) (*ListenerResponse, error)
	StopListener(context.Context, *ListenerRequest) (*ListenerResponse, error)
	GetStatus(*StatusRequest, grpc.ServerStreamingServer[StatusResponse]) error
	RegisterInit(context.Context, *InitRequest) (*InitResponse, error)
	NotifyNewConnection(context.Context, *ConnectionNotification) (*ConnectionResponse, error)
	BiDiStream(grpc.BidiStreamingServer[StreamMessage, StreamMessage]) error
	NotifyAgentCheckin(context.Context, *AgentCheckinNotification) (*AgentCheckinResponse, error)
	HandleUpload(context.Context, *HandleUploadRequest) (*HandleUploadResponse, error)
	mustEmbedUnimplementedAgentControlServer()
}

// UnimplementedAgentControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentControlServer struct{}

func (UnimplementedAgentControlServer) StartListener(context.Context, *ListenerRequest) (*ListenerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartListener not implemented")
}
func (UnimplementedAgentControlServer) StopListener(context.Context, *ListenerRequest) (*ListenerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopListener not implemented")
}
func (UnimplementedAgentControlServer) GetStatus(*StatusRequest, grpc.ServerStreamingServer[StatusResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedAgentControlServer) RegisterInit(context.Context, *InitRequest) (*InitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterInit not implemented")
}
func (UnimplementedAgentControlServer) NotifyNewConnection(context.Context, *ConnectionNotification) (*ConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyNewConnection not implemented")
}
func (UnimplementedAgentControlServer) BiDiStream(grpc.BidiStreamingServer[StreamMessage, StreamMessage]) error {
	return status.Errorf(codes.Unimplemented, "method BiDiStream not implemented")
}
func (UnimplementedAgentControlServer) NotifyAgentCheckin(context.Context, *AgentCheckinNotification) (*AgentCheckinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyAgentCheckin not implemented")
}
func (UnimplementedAgentControlServer) HandleUpload(context.Context, *HandleUploadRequest) (*HandleUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleUpload not implemented")
}
func (UnimplementedAgentControlServer) mustEmbedUnimplementedAgentControlServer() {}
func (UnimplementedAgentControlServer) testEmbeddedByValue()                      {}

// UnsafeAgentControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentControlServer will
// result in compilation errors.
type UnsafeAgentControlServer interface {
	mustEmbedUnimplementedAgentControlServer()
}

func RegisterAgentControlServer(s grpc.ServiceRegistrar, srv AgentControlServer) {
	// If the following call pancis, it indicates UnimplementedAgentControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentControl_ServiceDesc, srv)
}

func _AgentControl_StartListener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListenerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).StartListener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_StartListener_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).StartListener(ctx, req.(*ListenerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_StopListener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListenerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).StopListener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_StopListener_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).StopListener(ctx, req.(*ListenerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_GetStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentControlServer).GetStatus(m, &grpc.GenericServerStream[StatusRequest, StatusResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControl_GetStatusServer = grpc.ServerStreamingServer[StatusResponse]

func _AgentControl_RegisterInit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).RegisterInit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_RegisterInit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).RegisterInit(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_NotifyNewConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).NotifyNewConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_NotifyNewConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).NotifyNewConnection(ctx, req.(*ConnectionNotification))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_BiDiStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentControlServer).BiDiStream(&grpc.GenericServerStream[StreamMessage, StreamMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControl_BiDiStreamServer = grpc.BidiStreamingServer[StreamMessage, StreamMessage]

func _AgentControl_NotifyAgentCheckin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentCheckinNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).NotifyAgentCheckin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_NotifyAgentCheckin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).NotifyAgentCheckin(ctx, req.(*AgentCheckinNotification))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_HandleUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).HandleUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_HandleUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).HandleUpload(ctx, req.(*HandleUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentControl_ServiceDesc is the grpc.ServiceDesc for AgentControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.AgentControl",
	HandlerType: (*AgentControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartListener",
			Handler:    _AgentControl_StartListener_Handler,
		},
		{
			MethodName: "StopListener",
			Handler:    _AgentControl_StopListener_Handler,
		},
		{
			MethodName: "RegisterInit",
			Handler:    _AgentControl_RegisterInit_Handler,
		},
		{
			MethodName: "NotifyNewConnection",
			Handler:    _AgentControl_NotifyNewConnection_Handler,
		},
		{
			MethodName: "NotifyAgentCheckin",
			Handler:    _AgentControl_NotifyAgentCheckin_Handler,
		},
		{
			MethodName: "HandleUpload",
			Handler:    _AgentControl_HandleUpload_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetStatus",
			Handler:       _AgentControl_GetStatus_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BiDiStream",
			Handler:       _AgentControl_BiDiStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/service/agent.proto",
}
