// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/service/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListenerType int32

const (
	ListenerType_UNKNOWN ListenerType = 0
	ListenerType_HTTP    ListenerType = 1
	ListenerType_HTTPS   ListenerType = 2
	ListenerType_TCP     ListenerType = 3
	ListenerType_UDP     ListenerType = 4
)

// Enum value maps for ListenerType.
var (
	ListenerType_name = map[int32]string{
		0: "UNKNOWN",
		1: "HTTP",
		2: "HTTPS",
		3: "TCP",
		4: "UDP",
	}
	ListenerType_value = map[string]int32{
		"UNKNOWN": 0,
		"HTTP":    1,
		"HTTPS":   2,
		"TCP":     3,
		"UDP":     4,
	}
)

func (x ListenerType) Enum() *ListenerType {
	p := new(ListenerType)
	*p = x
	return p
}

func (x ListenerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListenerType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_service_agent_proto_enumTypes[0].Descriptor()
}

func (ListenerType) Type() protoreflect.EnumType {
	return &file_proto_service_agent_proto_enumTypes[0]
}

func (x ListenerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListenerType.Descriptor instead.
func (ListenerType) EnumDescriptor() ([]byte, []int) {
	return file_proto_service_agent_proto_rawDescGZIP(), []int{0}
}

type ListenerRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Name                  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port                  int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Type                  ListenerType           `protobuf:"varint,3,opt,name=type,proto3,enum=service.ListenerType" json:"type,omitempty"`
	Secure                bool                   `protobuf:"varint,4,opt,name=secure,proto3" json:"secure,omitempty"`
	BindIp                string                 `protobuf:"bytes,5,opt,name=bind_ip,json=bindIp,proto3" json:"bind_ip,omitempty"`
	GetProfile            string                 `protobuf:"bytes,6,opt,name=get_profile,json=getProfile,proto3" json:"get_profile,omitempty"`
	PostProfile           string                 `protobuf:"bytes,7,opt,name=post_profile,json=postProfile,proto3" json:"post_profile,omitempty"`
	ServerResponseProfile string                 `protobuf:"bytes,8,opt,name=server_response_profile,json=serverResponseProfile,proto3" json:"server_response_profile,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ListenerRequest) Reset() {
	*x = ListenerRequest{}
	mi := &file_proto_service_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenerRequest) ProtoMessage() {}

func (x *ListenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenerRequest.ProtoReflect.Descriptor instead.
func (*ListenerRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ListenerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListenerRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ListenerRequest) GetType() ListenerType {
	if x != nil {
		return x.Type
	}
	return ListenerType_UNKNOWN
}

func (x *ListenerRequest) GetSecure() bool {
	if x != nil {
		return x.Secure
	}
	return false
}

func (x *ListenerRequest) GetBindIp() string {
	if x != nil {
		return x.BindIp
	}
	return ""
}

func (x *ListenerRequest) GetGetProfile() string {
	if x != nil {
		return x.GetProfile
	}
	return ""
}

func (x *ListenerRequest) GetPostProfile() string {
	if x != nil {
		return x.PostProfile
	}
	return ""
}

func (x *ListenerRequest) GetServerResponseProfile() string {
	if x != nil {
		return x.ServerResponseProfile
	}
	return ""
}

type ListenerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenerResponse) Reset() {
	*x = ListenerResponse{}
	mi := &file_proto_service_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenerResponse) ProtoMessage() {}

func (x *ListenerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenerResponse.ProtoReflect.Descriptor instead.
func (*ListenerResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ListenerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListenerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListenerResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_service_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_agent_proto_rawDescGZIP(), []int{2}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Listeners     []*ActiveListener      `protobuf:"bytes,2,rep,name=listeners,proto3" json:"listeners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_service_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_agent_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusResponse) GetListeners() []*ActiveListener {
	if x != nil {
		return x.Listeners
	}
	return nil
}

type ActiveListener struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	StartTime     string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Connections   int32                  `protobuf:"varint,5,opt,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveListener) Reset() {
	*x = ActiveListener{}
	mi := &file_proto_service_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveListener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveListener) ProtoMessage() {}

func (x *ActiveListener) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveListener.ProtoReflect.Descriptor instead.
func (*ActiveListener) Descriptor() ([]byte, []int) {
	return file_proto_service_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ActiveListener) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActiveListener) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ActiveListener) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ActiveListener) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ActiveListener) GetConnections() int32 {
	if x != nil {
		return x.Connections
	}
	return 0
}

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Secret        string                 `protobuf:"bytes,4,opt,name=secret,proto3" json:"secret,omitempty"`
	Os            string                 `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,6,opt,name=arch,proto3" json:"arch,omitempty"`
	RsaKey        string                 `protobuf:"bytes,7,opt,name=rsa_key,json=rsaKey,proto3" json:"rsa_key,omitempty"`
	Protocol      string                 `protobuf:"bytes,8,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_proto_service_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_agent_proto_rawDescGZIP(), []int{5}
}

func (x *InitRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InitRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *InitRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InitRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *InitRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *InitRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *InitRequest) GetRsaKey() string {
	if x != nil {
		return x.RsaKey
	}
	return ""
}

func (x *InitRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_proto_service_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_agent_proto_rawDescGZIP(), []int{6}
}

func (x *InitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InitResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

type ConnectionNotification struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NewClientId    string                 `protobuf:"bytes,1,opt,name=new_client_id,json=newClientId,proto3" json:"new_client_id,omitempty"`
	ClientId       string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Protocol       string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Secret1        string                 `protobuf:"bytes,4,opt,name=secret1,proto3" json:"secret1,omitempty"`
	Secret2        string                 `protobuf:"bytes,5,opt,name=secret2,proto3" json:"secret2,omitempty"`
	ExtIp          string                 `protobuf:"bytes,6,opt,name=ext_ip,json=extIp,proto3" json:"ext_ip,omitempty"`
	IntIp          string                 `protobuf:"bytes,7,opt,name=int_ip,json=intIp,proto3" json:"int_ip,omitempty"`
	Username       string                 `protobuf:"bytes,8,opt,name=username,proto3" json:"username,omitempty"`
	Hostname       string                 `protobuf:"bytes,9,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Process        string                 `protobuf:"bytes,10,opt,name=process,proto3" json:"process,omitempty"`
	Pid            string                 `protobuf:"bytes,11,opt,name=pid,proto3" json:"pid,omitempty"`
	Arch           string                 `protobuf:"bytes,12,opt,name=arch,proto3" json:"arch,omitempty"`
	Os             string                 `protobuf:"bytes,13,opt,name=os,proto3" json:"os,omitempty"`
	Proto          string                 `protobuf:"bytes,14,opt,name=proto,proto3" json:"proto,omitempty"`
	LastSeen       int64                  `protobuf:"varint,15,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	ParentClientId string                 `protobuf:"bytes,16,opt,name=parent_client_id,json=parentClientId,proto3" json:"parent_client_id,omitempty"` // Parent agent's newClientID for linked agents
	LinkType       string                 `protobuf:"bytes,17,opt,name=link_type,json=linkType,proto3" json:"link_type,omitempty"`                     // Link type (e.g., "smb") for linked agents
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConnectionNotification) Reset() {
	*x = ConnectionNotification{}
	mi := &file_proto_service_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionNotification) ProtoMessage() {}

func (x *ConnectionNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionNotification.ProtoReflect.Descriptor instead.
func (*ConnectionNotification) Descriptor() ([]byte, []int) {
	return file_proto_service_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ConnectionNotification) GetNewClientId() string {
	if x != nil {
		return x.NewClientId
	}
	return ""
}

func (x *ConnectionNotification) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ConnectionNotification) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ConnectionNotification) GetSecret1() string {
	if x != nil {
		return x.Secret1
	}
	return ""
}

func (x *ConnectionNotification) GetSecret2() string {
	if x != nil {
		return x.Secret2
	}
	return ""
}

func (x *ConnectionNotification) GetExtIp() string {
	if x != nil {
		return x.ExtIp
	}
	return ""
}

func (x *ConnectionNotification) GetIntIp() string {
	if x != nil {
		return x.IntIp
	}
	return ""
}

func (x *ConnectionNotification) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ConnectionNotification) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ConnectionNotification) GetProcess() string {
	if x != nil {
		return x.Process
	}
	return ""
}

func (x *ConnectionNotification) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *ConnectionNotification) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *ConnectionNotification) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *ConnectionNotification) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *ConnectionNotification) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *ConnectionNotification) GetParentClientId() string {
	if x != nil {
		return x.ParentClientId
	}
	return ""
}

func (x *ConnectionNotification) GetLinkType() string {
	if x != nil {
		return x.LinkType
	}
	return ""
}

type ConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionResponse) Reset() {
	*x = ConnectionResponse{}
	mi := &file_proto_service_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionResponse) ProtoMessage() {}

func (x *ConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionResponse.ProtoReflect.Descriptor instead.
func (*ConnectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ConnectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConnectionResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

// Define messages for bidirectional streaming
type StreamMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`        // Identifier of the sender (e.g., "agent_service", "websocket_service")
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`            // Type of message ("notification", "command", "response", "agent_command")
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`      // The message content (JSON-encoded data based on message type)
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Timestamp of the message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessage) Reset() {
	*x = StreamMessage{}
	mi := &file_proto_service_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessage) ProtoMessage() {}

func (x *StreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessage.ProtoReflect.Descriptor instead.
func (*StreamMessage) Descriptor() ([]byte, []int) {
	return file_proto_service_agent_proto_rawDescGZIP(), []int{9}
}

func (x *StreamMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *StreamMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StreamMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StreamMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Define the agent_command content format
type AgentCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`                      // The command to execute
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`       // The ID of the target agent
	CommandId     string                 `protobuf:"bytes,3,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // A unique ID for the command
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                  // ISO 8601 timestamp when the command was sent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCommand) Reset() {
	*x = AgentCommand{}
	mi := &file_proto_service_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCommand) ProtoMessage() {}

func (x *AgentCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCommand.ProtoReflect.Descriptor instead.
func (*AgentCommand) Descriptor() ([]byte, []int) {
	return file_proto_service_agent_proto_rawDescGZIP(), []int{10}
}

func (x *AgentCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *AgentCommand) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *AgentCommand) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// Add new message types for agent check-ins
type AgentCheckinNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	LastSeen      int64                  `protobuf:"varint,2,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCheckinNotification) Reset() {
	*x = AgentCheckinNotification{}
	mi := &file_proto_service_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCheckinNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCheckinNotification) ProtoMessage() {}

func (x *AgentCheckinNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCheckinNotification.ProtoReflect.Descriptor instead.
func (*AgentCheckinNotification) Descriptor() ([]byte, []int) {
	return file_proto_service_agent_proto_rawDescGZIP(), []int{11}
}

func (x *AgentCheckinNotification) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentCheckinNotification) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

type AgentCheckinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCheckinResponse) Reset() {
	*x = AgentCheckinResponse{}
	mi := &file_proto_service_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCheckinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCheckinResponse) ProtoMessage() {}

func (x *AgentCheckinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCheckinResponse.ProtoReflect.Descriptor instead.
func (*AgentCheckinResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_agent_proto_rawDescGZIP(), []int{12}
}

func (x *AgentCheckinResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AgentCheckinResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AgentCheckinResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

type HandleUploadRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AgentId          string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	OriginalFilename string                 `protobuf:"bytes,2,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"`
	CurrentFilename  string                 `protobuf:"bytes,3,opt,name=current_filename,json=currentFilename,proto3" json:"current_filename,omitempty"`
	RemotePath       string                 `protobuf:"bytes,4,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	Timestamp        string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HandleUploadRequest) Reset() {
	*x = HandleUploadRequest{}
	mi := &file_proto_service_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleUploadRequest) ProtoMessage() {}

func (x *HandleUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleUploadRequest.ProtoReflect.Descriptor instead.
func (*HandleUploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_agent_proto_rawDescGZIP(), []int{13}
}

func (x *HandleUploadRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HandleUploadRequest) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

func (x *HandleUploadRequest) GetCurrentFilename() string {
	if x != nil {
		return x.CurrentFilename
	}
	return ""
}

func (x *HandleUploadRequest) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

func (x *HandleUploadRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type HandleUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleUploadResponse) Reset() {
	*x = HandleUploadResponse{}
	mi := &file_proto_service_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleUploadResponse) ProtoMessage() {}

func (x *HandleUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleUploadResponse.ProtoReflect.Descriptor instead.
func (*HandleUploadResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_agent_proto_rawDescGZIP(), []int{14}
}

func (x *HandleUploadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HandleUploadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAgentRequest) Reset() {
	*x = RemoveAgentRequest{}
	mi := &file_proto_service_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAgentRequest) ProtoMessage() {}

func (x *RemoveAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAgentRequest.ProtoReflect.Descriptor instead.
func (*RemoveAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_agent_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RemoveAgentRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type RemoveAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAgentResponse) Reset() {
	*x = RemoveAgentResponse{}
	mi := &file_proto_service_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAgentResponse) ProtoMessage() {}

func (x *RemoveAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAgentResponse.ProtoReflect.Descriptor instead.
func (*RemoveAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_agent_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveAgentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_service_agent_proto protoreflect.FileDescriptor

const file_proto_service_agent_proto_rawDesc = "" +
	"\n" +
	"\x19proto/service/agent.proto\x12\aservice\"\x95\x01\n" +
	"\x0fListenerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12)\n" +
	"\x04type\x18\x03 \x01(\x0e2\x15.service.ListenerTypeR\x04type\x12\x16\n" +
	"\x06secure\x18\x04 \x01(\bR\x06secure\x12\x17\n" +
	"\abind_ip\x18\x05 \x01(\tR\x06bindIp\"e\n" +
	"\x10ListenerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x05R\terrorCode\"\x0f\n" +
	"\rStatusRequest\"_\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x125\n" +
	"\tlisteners\x18\x02 \x03(\v2\x17.service.ActiveListenerR\tlisteners\"\x91\x01\n" +
	"\x0eActiveListener\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12 \n" +
	"\vconnections\x18\x05 \x01(\x05R\vconnections\"\xbf\x01\n" +
	"\vInitRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06secret\x18\x04 \x01(\tR\x06secret\x12\x0e\n" +
	"\x02os\x18\x05 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x06 \x01(\tR\x04arch\x12\x17\n" +
	"\arsa_key\x18\a \x01(\tR\x06rsaKey\x12\x1a\n" +
	"\bprotocol\x18\b \x01(\tR\bprotocol\"a\n" +
	"\fInitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x05R\terrorCode\"\xd9\x03\n" +
	"\x16ConnectionNotification\x12\"\n" +
	"\rnew_client_id\x18\x01 \x01(\tR\vnewClientId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x18\n" +
	"\asecret1\x18\x04 \x01(\tR\asecret1\x12\x18\n" +
	"\asecret2\x18\x05 \x01(\tR\asecret2\x12\x15\n" +
	"\x06ext_ip\x18\x06 \x01(\tR\x05extIp\x12\x15\n" +
	"\x06int_ip\x18\a \x01(\tR\x05intIp\x12\x1a\n" +
	"\busername\x18\b \x01(\tR\busername\x12\x1a\n" +
	"\bhostname\x18\t \x01(\tR\bhostname\x12\x18\n" +
	"\aprocess\x18\n" +
	" \x01(\tR\aprocess\x12\x10\n" +
	"\x03pid\x18\v \x01(\tR\x03pid\x12\x12\n" +
	"\x04arch\x18\f \x01(\tR\x04arch\x12\x0e\n" +
	"\x02os\x18\r \x01(\tR\x02os\x12\x14\n" +
	"\x05proto\x18\x0e \x01(\tR\x05proto\x12\x1b\n" +
	"\tlast_seen\x18\x0f \x01(\x03R\blastSeen\x12(\n" +
	"\x10parent_client_id\x18\x10 \x01(\tR\x0eparentClientId\x12\x1b\n" +
	"\tlink_type\x18\x11 \x01(\tR\blinkType\"g\n" +
	"\x12ConnectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x05R\terrorCode\"s\n" +
	"\rStreamMessage\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x80\x01\n" +
	"\fAgentCommand\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x03 \x01(\tR\tcommandId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"R\n" +
	"\x18AgentCheckinNotification\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tlast_seen\x18\x02 \x01(\x03R\blastSeen\"i\n" +
	"\x14AgentCheckinResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x05R\terrorCode\"\xc7\x01\n" +
	"\x13HandleUploadRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12+\n" +
	"\x11original_filename\x18\x02 \x01(\tR\x10originalFilename\x12)\n" +
	"\x10current_filename\x18\x03 \x01(\tR\x0fcurrentFilename\x12\x1f\n" +
	"\vremote_path\x18\x04 \x01(\tR\n" +
	"remotePath\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\"J\n" +
	"\x14HandleUploadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"K\n" +
	"\x12RemoveAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"I\n" +
	"\x13RemoveAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*B\n" +
	"\fListenerType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04HTTP\x10\x01\x12\t\n" +
	"\x05HTTPS\x10\x02\x12\a\n" +
	"\x03TCP\x10\x03\x12\a\n" +
	"\x03UDP\x10\x042\xd4\x04\n" +
	"\fAgentControl\x12D\n" +
	"\rStartListener\x12\x18.service.ListenerRequest\x1a\x19.service.ListenerResponse\x12C\n" +
	"\fStopListener\x12\x18.service.ListenerRequest\x1a\x19.service.ListenerResponse\x12>\n" +
	"\tGetStatus\x12\x16.service.StatusRequest\x1a\x17.service.StatusResponse0\x01\x12;\n" +
	"\fRegisterInit\x12\x14.service.InitRequest\x1a\x15.service.InitResponse\x12S\n" +
	"\x13NotifyNewConnection\x12\x1f.service.ConnectionNotification\x1a\x1b.service.ConnectionResponse\x12@\n" +
	"\n" +
	"BiDiStream\x12\x16.service.StreamMessage\x1a\x16.service.StreamMessage(\x010\x01\x12V\n" +
	"\x12NotifyAgentCheckin\x12!.service.AgentCheckinNotification\x1a\x1d.service.AgentCheckinResponse\x12M\n" +
	"\fHandleUpload\x12\x1c.service.HandleUploadRequest\x1a\x1d.service.HandleUploadResponse\"\x00B\n" +
	"Z\bc2/protob\x06proto3"

var (
	file_proto_service_agent_proto_rawDescOnce sync.Once
	file_proto_service_agent_proto_rawDescData []byte
)

func file_proto_service_agent_proto_rawDescGZIP() []byte {
	file_proto_service_agent_proto_rawDescOnce.Do(func() {
		file_proto_service_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_service_agent_proto_rawDesc), len(file_proto_service_agent_proto_rawDesc)))
	})
	return file_proto_service_agent_proto_rawDescData
}

var file_proto_service_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_service_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_service_agent_proto_goTypes = []any{
	(ListenerType)(0),                // 0: service.ListenerType
	(*ListenerRequest)(nil),          // 1: service.ListenerRequest
	(*ListenerResponse)(nil),         // 2: service.ListenerResponse
	(*StatusRequest)(nil),            // 3: service.StatusRequest
	(*StatusResponse)(nil),           // 4: service.StatusResponse
	(*ActiveListener)(nil),           // 5: service.ActiveListener
	(*InitRequest)(nil),              // 6: service.InitRequest
	(*InitResponse)(nil),             // 7: service.InitResponse
	(*ConnectionNotification)(nil),   // 8: service.ConnectionNotification
	(*ConnectionResponse)(nil),       // 9: service.ConnectionResponse
	(*StreamMessage)(nil),            // 10: service.StreamMessage
	(*AgentCommand)(nil),             // 11: service.AgentCommand
	(*AgentCheckinNotification)(nil), // 12: service.AgentCheckinNotification
	(*AgentCheckinResponse)(nil),     // 13: service.AgentCheckinResponse
	(*HandleUploadRequest)(nil),      // 14: service.HandleUploadRequest
	(*HandleUploadResponse)(nil),     // 15: service.HandleUploadResponse
	(*RemoveAgentRequest)(nil),       // 16: service.RemoveAgentRequest
	(*RemoveAgentResponse)(nil),      // 17: service.RemoveAgentResponse
}
var file_proto_service_agent_proto_depIdxs = []int32{
	0,  // 0: service.ListenerRequest.type:type_name -> service.ListenerType
	5,  // 1: service.StatusResponse.listeners:type_name -> service.ActiveListener
	1,  // 2: service.AgentControl.StartListener:input_type -> service.ListenerRequest
	1,  // 3: service.AgentControl.StopListener:input_type -> service.ListenerRequest
	3,  // 4: service.AgentControl.GetStatus:input_type -> service.StatusRequest
	6,  // 5: service.AgentControl.RegisterInit:input_type -> service.InitRequest
	8,  // 6: service.AgentControl.NotifyNewConnection:input_type -> service.ConnectionNotification
	10, // 7: service.AgentControl.BiDiStream:input_type -> service.StreamMessage
	12, // 8: service.AgentControl.NotifyAgentCheckin:input_type -> service.AgentCheckinNotification
	14, // 9: service.AgentControl.HandleUpload:input_type -> service.HandleUploadRequest
	2,  // 10: service.AgentControl.StartListener:output_type -> service.ListenerResponse
	2,  // 11: service.AgentControl.StopListener:output_type -> service.ListenerResponse
	4,  // 12: service.AgentControl.GetStatus:output_type -> service.StatusResponse
	7,  // 13: service.AgentControl.RegisterInit:output_type -> service.InitResponse
	9,  // 14: service.AgentControl.NotifyNewConnection:output_type -> service.ConnectionResponse
	10, // 15: service.AgentControl.BiDiStream:output_type -> service.StreamMessage
	13, // 16: service.AgentControl.NotifyAgentCheckin:output_type -> service.AgentCheckinResponse
	15, // 17: service.AgentControl.HandleUpload:output_type -> service.HandleUploadResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_service_agent_proto_init() }
func file_proto_service_agent_proto_init() {
	if File_proto_service_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_agent_proto_rawDesc), len(file_proto_service_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_agent_proto_goTypes,
		DependencyIndexes: file_proto_service_agent_proto_depIdxs,
		EnumInfos:         file_proto_service_agent_proto_enumTypes,
		MessageInfos:      file_proto_service_agent_proto_msgTypes,
	}.Build()
	File_proto_service_agent_proto = out.File
	file_proto_service_agent_proto_goTypes = nil
	file_proto_service_agent_proto_depIdxs = nil
}
